provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  date:
    lang: java8
    handler: ./date
    image: s8sg/date:latest

  date-python:
    lang: python
    handler: ./date-python
    image: s8sg/date-python:latest

  date-flow:
    lang: faas-flow
    handler: ./date-flow
    image: s8sg/date-flow:latest
    environment:
       gateway: "gateway:8080"
       workflow_name: "date-flow"
       date-function: "date-python"
