provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  date-java:
    lang: java8
    handler: ./date-java
    image: s8sg/date:latest

  date-node:
    lang: node
    handler: ./date-node
    image: date-node:latest

  date-go:
    lang: go
    handler: ./date-go
    image: date-go:latest

  date-python:
    lang: python
    handler: ./date-python
    image: s8sg/date-python:latest

  date-flow:
    lang: faas-flow
    handler: ./date-flow
    image: s8sg/date-flow:latest
    environment:
       gateway: "gateway:8080"
       workflow_name: "date-flow"
       date-function: "date-java"
       # date-function: "date-node"
       # date-function: "date-python"
       # date-function: "date-go"

  test-java:
    lang: go
    handler: ./test-java
    image: test-java:latest
    environment:
       gateway: "gateway:8080"
       date-function: "date-java"
